# =============开发环境配置==============
server:
  # 服务器的HTTP端口，默认为8080
  port: 8089


# =============Spring配置==============
spring:
  # 应用名称
  application:
    name: batch-test
  # 激活使用的配置文件
  profiles:
    active: mybatisplus,dev
  datasource:
    url: jdbc:mysql://8.129.130.21:3306/manage-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: luqiao
    password: luqiao
    driver-class-name: com.mysql.cj.jdbc.Driver

