spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=UTC
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos的 server地址（不用写 http://）
        server-addr: localhost:8848
#        namespace: 0190018d-6584-4250-943a-62c1c07ee365
#        # 假设北京机房集群
        cluster-name: BJ
  application:
    name: user-center

server:
  port: 8030

rocketmq:
  name-server: 127.0.0.1:9876